# GitHub Actions Workflow for Building and Deploying ASP.NET Core App to Azure Web App

name: Build and deploy ASP.Net Core app to Azure Web App - project231

on:
  push:
    branches:
      - Pum2
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      # Build và publish từng project riêng biệt để tránh lỗi xung đột file cấu hình
      - name: Publish DOINHE1_API
        run: dotnet publish D:\a\DOINHE\DOINHE\DOINHE1_API\DOINHE1_API.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp/DOINHE1_API

      - name: Publish DOINHE_BusinessObject
        run: dotnet publish D:\a\DOINHE\DOINHE\DOINHE_BusinessObject\DOINHE_BusinessObject.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp/DOINHE_BusinessObject

      - name: Publish DOINHE_DataAccess
        run: dotnet publish D:\a\DOINHE\DOINHE\DOINHE_DataAccess\DOINHE_DataAccess.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp/DOINHE_DataAccess

      - name: Publish DOINHE_Repository
        run: dotnet publish D:\a\DOINHE\DOINHE\DOINHE_Repository\DOINHE_Repository.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp/DOINHE_Repository

      - name: Publish DOINHE
        run: dotnet publish D:\a\DOINHE\DOINHE\DOINHE\DOINHE.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp/DOINHE

      - name: Upload artifacts for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1ABAE108D731460C83A415E1843BB423 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_76B09964DE4440BD95A0700B4DB2DDAB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_29AB5E29A83E4EAB857765B2AE068657 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'project231'
          slot-name: 'Production'
          package: '${{env.DOTNET_ROOT}}/myapp/DOINHE1_API' # Đường dẫn này có thể được tùy chỉnh nếu cần deploy một project cụ thể
